In [35]:
import pandas as pd 
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [36]:
import tensorflow as tf

In [37]:
sm =pd.read_csv(r"C:\Users\shrus\Downloads\spam1.csv", encoding ='cp1252')

In [38]:
sm =sm.rename(columns ={'v1':'Y', 'v2': 'X'})

In [39]:
sm.Y =sm.Y.replace({'ham':0 ,'spam':1})

In [40]:
from sklearn.model_selection import train_test_split
train ,test =train_test_split(sm, test_size =.2)

In [41]:
train_x =train.iloc[: ,1]
train_y =train.iloc[:,0]

test_x =test.iloc[:,1]
test_y =test.iloc[:,0] # u had mentione 1

In [42]:
train_y

3395    0
1678    1
3891    0
4796    0
1916    1
       ..
5958    0
701     0
4469    0
889     0
3948    0
Name: Y, Length: 5420, dtype: int64

In [135]:
from keras.layers import Dense,SimpleRNN, Embedding
from keras.models import Sequential
from tensorflow.keras.utils import to_categorical

In [44]:
train_y =to_categorical(train_y)

In [45]:
train_y

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], shape=(5420, 2))

In [46]:
max_num_words =10000 ##how many words do we consider from the entire corpus
seq_len =50           #
embedding_size =100   #vector length of each word
from tensorflow.keras.preprocessing.text import Tokenizer #assign a number to each word
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [47]:
tokenizer =Tokenizer(num_words =max_num_words)
tokenizer.fit_on_texts(sm.X)
train_x =tokenizer.texts_to_sequences(train_x)
train_x = pad_sequences(train_x, maxlen= seq_len)

In [48]:
type(train_x)

numpy.ndarray

In [49]:
train_x

array([[   0,    0,    0, ..., 1340,   13,  216],
       [   0,    0,    0, ..., 2531, 1866,  349],
       [   0,    0,    0, ...,    0,    0,  693],
       ...,
       [   0,    0,    0, ...,   75, 4576,   47],
       [   0,    0,    0, ...,  670,   49,  385],
       [   0,    0,    0, ..., 1995, 1995,  178]],
      shape=(5420, 50), dtype=int32)

In [50]:
test_x = tokenizer.texts_to_sequences(test_x)
test_x=pad_sequences(test_x, maxlen=seq_len)

In [69]:
model=Sequential()
model.add(Embedding(input_dim=max_num_words,
                   input_length = seq_len,
                   output_dim=embedding_size))
model.add(SimpleRNN(55))
model.add(Dense(2,activation='softmax'))
from tensorflow.keras.optimizers import Adam
adam=Adam(learning_rate= .001)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [70]:
model.fit(train_x,train_y,epochs=5,batch_size=32,validation_split=.2)

Epoch 1/5
136/136 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - accuracy: 0.9267 - loss: 0.2020 - val_accuracy: 0.9889 - val_loss: 0.0505
Epoch 2/5
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - accuracy: 0.9942 - loss: 0.0239 - val_accuracy: 0.9779 - val_loss: 0.0677
Epoch 3/5
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - accuracy: 0.9986 - loss: 0.0055 - val_accuracy: 0.9871 - val_loss: 0.0451
Epoch 4/5
136/136 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - accuracy: 0.9995 - loss: 0.0027 - val_accuracy: 0.9899 - val_loss: 0.0425
Epoch 5/5
136/136 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step - accuracy: 0.9998 - loss: 0.0012 - val_accuracy: 0.9908 - val_loss: 0.0465

In [71]:
pred = model.predict(test_x)
pred_cat = pred.argmax(axis=1)
from sklearn.metrics import *
tab = confusion_matrix(test_y,pred_cat)
tab
tab.diagonal().sum() / tab.sum() *100

43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step

np.float64(98.74631268436578)

In [72]:
model.save("spam_ham_Oct122026.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [55]:
tab

array([[1191,    1],
       [  23,  141]])

In [56]:
# pred = model.predict(test_pad)
# pred_cate = pred.argmax(axis=1)

# from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# tab = confusion_matrix(test_y, pred_cate)

# print("Confusion Matrix:")
# print(tab)

# print("\nAccuracy:", accuracy_score(test_y, pred_cate) * 100, "%")

In [77]:
afr=pd.read_clipboard("")

In [78]:
afr.head()

   Score        Time                Summary
0      5  1303862400  Good Quality Dog Food
1      1  1346976000      Not as Advertised
2      4  1219017600    Delight says it all
3      2  1307923200         Cough Medicine
4      5  1350777600            Great taffy

In [79]:
afr = afr.drop(['Time'], axis =1)

In [81]:
afr=afr.rename(columns ={'Score':'Y','Summary':'X'})

In [89]:
afr['X'] = afr['X'].fillna('').astype(str).str.lower()

In [90]:
from sklearn.model_selection import train_test_split
train ,test =train_test_split(afr, test_size =.2)

In [91]:
train_x =train.iloc[: ,1]
train_y =train.iloc[:,0]

test_x =test.iloc[:,1]
test_y =test.iloc[:,0]

In [92]:
train_y =to_categorical(train_y)

In [93]:
max_num_words =10000 ##how many words do we consider from the entire corpus
seq_len =50           #
embedding_size =100   #vector length of each word
from tensorflow.keras.preprocessing.text import Tokenizer #assign a number to each word
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [95]:
tokenizer =Tokenizer(num_words =max_num_words)
tokenizer.fit_on_texts(afr.X)
train_x =tokenizer.texts_to_sequences(train_x)
train_x = pad_sequences(train_x, maxlen= seq_len)

In [96]:
test_x = tokenizer.texts_to_sequences(test_x)
test_x=pad_sequences(test_x, maxlen=seq_len)

In [99]:
model=Sequential()
model.add(Embedding(input_dim=max_num_words,
                   input_length = seq_len,
                   output_dim=embedding_size))
model.add(SimpleRNN(55))
model.add(Dense(6,activation='softmax'))
from tensorflow.keras.optimizers import Adam
adam=Adam(learning_rate= .001)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [100]:
model.fit(train_x,train_y,epochs=5,batch_size=32,validation_split=.2)

Epoch 1/5
11357/11357 ━━━━━━━━━━━━━━━━━━━━ 288s 25ms/step - accuracy: 0.7202 - loss: 0.7744 - val_accuracy: 0.7355 - val_loss: 0.7268
Epoch 2/5
11357/11357 ━━━━━━━━━━━━━━━━━━━━ 365s 29ms/step - accuracy: 0.7551 - loss: 0.6684 - val_accuracy: 0.7505 - val_loss: 0.6899
Epoch 3/5
11357/11357 ━━━━━━━━━━━━━━━━━━━━ 332s 29ms/step - accuracy: 0.7755 - loss: 0.6156 - val_accuracy: 0.7574 - val_loss: 0.6819
Epoch 4/5
11357/11357 ━━━━━━━━━━━━━━━━━━━━ 351s 27ms/step - accuracy: 0.7899 - loss: 0.5755 - val_accuracy: 0.7597 - val_loss: 0.6833
Epoch 5/5
11357/11357 ━━━━━━━━━━━━━━━━━━━━ 19036s 2s/step - accuracy: 0.8023 - loss: 0.5435 - val_accuracy: 0.7606 - val_loss: 0.6869

In [102]:
pred = model.predict(test_x)
pred_cat = pred.argmax(axis=1)
from sklearn.metrics import *
tab = confusion_matrix(test_y,pred_cat)
tab
tab.diagonal().sum() / tab.sum() *100

3550/3550 ━━━━━━━━━━━━━━━━━━━━ 46s 13ms/step

np.float64(75.84485339438231)

In [101]:
#tripadvisor
#fake job posting
#combine anyone with streamlit

In [117]:
ta=pd.read_csv(r"C:\Users\shrus\Downloads\Trip_advisor_review.csv")

In [118]:
ta.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [119]:
ta=ta.rename(columns ={'Rating':'Y','Review':'X'})

In [136]:
X = afr['X'].fillna('').astype(str)
y = afr['Y'].astype(int)

In [137]:
from sklearn.model_selection import train_test_split
train_text, test_text, train_y, test_y = train_test_split( X, y,test_size=0.2, random_state=42,stratify=y)

In [138]:
tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(train_text)

In [139]:
train_x = tokenizer.texts_to_sequences(train_text)
test_x = tokenizer.texts_to_sequences(test_text)

In [140]:
train_x = pad_sequences(train_x, maxlen=seq_len)
test_x = pad_sequences(test_x, maxlen=seq_len)

In [141]:
train_y = to_categorical(train_y.to_numpy() - 1, num_classes=5)
test_y = to_categorical(test_y.to_numpy() - 1, num_classes=5)

In [149]:

model = Sequential([
    Embedding(
        input_dim=max_num_words,
        output_dim=64
    ),
    SimpleRNN(64),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(5, activation='softmax')
])
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [150]:
model.fit(train_x,train_y,epochs=5,batch_size=32,validation_split=.2)

Epoch 1/5
11357/11357 ━━━━━━━━━━━━━━━━━━━━ 380s 33ms/step - accuracy: 0.7130 - loss: 0.7911 - val_accuracy: 0.7279 - val_loss: 0.7352
Epoch 2/5
11357/11357 ━━━━━━━━━━━━━━━━━━━━ 367s 32ms/step - accuracy: 0.7429 - loss: 0.7023 - val_accuracy: 0.7450 - val_loss: 0.7079
Epoch 3/5
11357/11357 ━━━━━━━━━━━━━━━━━━━━ 345s 29ms/step - accuracy: 0.7570 - loss: 0.6643 - val_accuracy: 0.7459 - val_loss: 0.7024
Epoch 4/5
11357/11357 ━━━━━━━━━━━━━━━━━━━━ 398s 31ms/step - accuracy: 0.7678 - loss: 0.6372 - val_accuracy: 0.7512 - val_loss: 0.6866
Epoch 5/5
11357/11357 ━━━━━━━━━━━━━━━━━━━━ 373s 30ms/step - accuracy: 0.7763 - loss: 0.6154 - val_accuracy: 0.7552 - val_loss: 0.6916

In [153]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
pred = model.predict(test_x)
pred_cat = pred.argmax(axis=1)
test_y_cat = test_y.argmax(axis=1)
tab = confusion_matrix(test_y_cat, pred_cat)
accuracy = tab.diagonal().sum() / tab.sum() * 100
print("Accuracy:", accuracy, "%")

3550/3550 ━━━━━━━━━━━━━━━━━━━━ 38s 11ms/step
Accuracy: 75.49176719204014 %

In [156]:
job=pd.read_csv(r"C:\Users\shrus\Downloads\fake_job_postings.csv.xls")

In [157]:
job.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [158]:
job['X'] = job['company_profile'].apply(str) + " " + job['salary_range'].apply(str) + " " + job['requirements'].apply(str) + " " + job['benefits'].apply(str) + " " + job['location'].apply(str) + " " + job['description'].apply(str) + " " +job['industry'].apply(str)

In [159]:
job =job.rename(columns={'fraudulent':'Y'})

In [160]:
df = job.loc[:, ['X', 'Y']]

In [161]:
afr['X'] = afr['X'].fillna('').astype(str).str.lower()

In [169]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [170]:
X = job['X'].fillna('').astype(str)
y = job['Y'].astype(int)

In [171]:
train_text, test_text, train_y, test_y = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [172]:
train_y = to_categorical(train_y.to_numpy() - 1, num_classes=5)
test_y = to_categorical(test_y.to_numpy() - 1, num_classes=5)

In [173]:
tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(train_text)

In [174]:
train_x = tokenizer.texts_to_sequences(train_text)
test_x = tokenizer.texts_to_sequences(test_text)

In [175]:
train_x = pad_sequences(train_x, maxlen=seq_len)
test_x = pad_sequences(test_x, maxlen=seq_len)

In [176]:
model = Sequential([
    Embedding(
        input_dim=max_num_words,
        output_dim=64
    ),
    SimpleRNN(64),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(5, activation='softmax')
])
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [177]:
model.fit(train_x,train_y,epochs=5,batch_size=32,validation_split=.2)

Epoch 1/5
358/358 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9422 - loss: 0.2283 - val_accuracy: 0.9595 - val_loss: 0.1365
Epoch 2/5
358/358 ━━━━━━━━━━━━━━━━━━━━ 10s 27ms/step - accuracy: 0.9692 - loss: 0.1104 - val_accuracy: 0.9598 - val_loss: 0.1409
Epoch 3/5
358/358 ━━━━━━━━━━━━━━━━━━━━ 12s 32ms/step - accuracy: 0.9858 - loss: 0.0458 - val_accuracy: 0.9699 - val_loss: 0.1236
Epoch 4/5
358/358 ━━━━━━━━━━━━━━━━━━━━ 11s 30ms/step - accuracy: 0.9955 - loss: 0.0153 - val_accuracy: 0.9696 - val_loss: 0.1423
Epoch 5/5
358/358 ━━━━━━━━━━━━━━━━━━━━ 11s 31ms/step - accuracy: 0.9983 - loss: 0.0060 - val_accuracy: 0.9602 - val_loss: 0.1853

In [178]:
pred = model.predict(test_x)
pred_cat = pred.argmax(axis=1)
test_y_cat = test_y.argmax(axis=1)
tab = confusion_matrix(test_y_cat, pred_cat)
accuracy = tab.diagonal().sum() / tab.sum() * 100
print("Accuracy:", accuracy, "%")

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step
Accuracy: 95.6096196868009 %

In [180]:
# Save the trained RNN model
model.save(r"C:\Users\shrus\Downloads\rnn_model.keras")

print("RNN model saved successfully!")

RNN model saved successfully!

In [181]:
import pickle

with open(r"C:\Users\shrus\Downloads\tokenizer.pkl", "wb") as file:
    pickle.dump(tokenizer, file)

print("Tokenizer saved successfully!")

Tokenizer saved successfully!

In [182]:
import os

print("Model exists:",
      os.path.exists(r"C:\Users\shrus\Downloads\rnn_model.keras"))

print("Tokenizer exists:",
      os.path.exists(r"C:\Users\shrus\Downloads\tokenizer.pkl"))

Model exists: True
Tokenizer exists: True

In [183]:
from tensorflow.keras.models import load_model

loaded_model = load_model(
    r"C:\Users\shrus\Downloads\rnn_model.keras"
)

loaded_model.summary()

Model: "sequential_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_15 (Embedding)             │ (None, 50, 64)              │         640,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_12 (SimpleRNN)            │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_5 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_20 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_21 (Dense)                     │ (None, 5)                   │             165 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,951,505 (7.44 MB)

 Trainable params: 650,501 (2.48 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,301,004 (4.96 MB)

In [184]:
print(model.summary())
print(tokenizer)

Model: "sequential_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_15 (Embedding)             │ (None, 50, 64)              │         640,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_12 (SimpleRNN)            │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_5 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_20 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_21 (Dense)                     │ (None, 5)                   │             165 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,951,505 (7.44 MB)

 Trainable params: 650,501 (2.48 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,301,004 (4.96 MB)

None
<keras.src.legacy.preprocessing.text.Tokenizer object at 0x000002320A4DADD0>

In [185]:
print("Tokenizer:", type(tokenizer))
print("Maximum sequence length: 50")
print("Label encoder:", type(label_encoder) if 'label_encoder' in globals() else "Not found")

Tokenizer: <class 'keras.src.legacy.preprocessing.text.Tokenizer'>
Maximum sequence length: 50
Label encoder: Not found